---

base_archiving_tools:
  - p7zip-full
  - unzip  
  - zip

base_system_tools:
  - fatrace
  - progress
  - pwgen

base_download_tools:
  - wget

base_developer_tools:
  - ansible-lint
  - curl
  - git
  - git-extras
  - gitg
  - golang-go
  - htop
  - httpie
  - jq  
  - netcat
  - nmap
  - nodejs
  - pssh
  - python3-pip
  - python-pip
  - shellcheck
  - siege
  - sslscan
  - tmux
  - tree
  - uget
  - xclip
  - yamllint
  - docker.io

base_git_bash_prompt_url: "https://github.com/magicmonty/bash-git-prompt.git"

# direct install link instead of using ppa
#base_qownnotes_url: "https://launchpad.net/~pbek/+archive/ubuntu/qownnotes/+build/13855881/+files/qownnotes_17.12.5-1ubuntu3ppa1~artful1_amd64.deb"

base_openssh_server:
  apt_package: openssh-server
  service: ssh
...
